#!/bin/bash
#
# Run-level Startup script for the Oracle Instance and Listener
#
### BEGIN INIT INFO
# Provides:          Oracle
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup/Shutdown Oracle listener and instance
### END INIT INFO

ORA_HOME="/u01/app/oracle/product/11.2.0/dbhome_1"
ORA_OWNR="oracle"

# if the executables do not exist -- display error

if [ ! -f $ORA_HOME/bin/dbstart -o ! -d $ORA_HOME ]
then
        echo "Oracle startup: cannot start"
        exit 1
fi

# depending on parameter -- startup, shutdown, restart
# of the instance and listener or usage display

case "$1" in
        start)
                # Oracle listener and instance startup
                echo -n "Starting Oracle: "
                su - $ORA_OWNR -c "$ORA_HOME/bin/dbstart $ORA_HOME"
                su - $ORA_OWNR -c "$ORA_HOME/bin/lsnrctl start"

                #Optional : for Enterprise Manager software only
                su - $ORA_OWNR -c "$ORA_HOME/bin/emctl start dbconsole"

                touch /var/lock/oracle
                echo "OK"
                ;;
        stop)
                # Oracle listener and instance shutdown
                echo -n "Shutdown Oracle: "

                #Optional : for Enterprise Manager software only
                su - $ORA_OWNR -c "$ORA_HOME/bin/emctl stop dbconsole"

                su - $ORA_OWNR -c "$ORA_HOME/bin/lsnrctl stop"
                su - $ORA_OWNR -c "$ORA_HOME/bin/dbshut $ORA_HOME"
                rm -f /var/lock/oracle
                echo "OK"
                ;;
        reload|restart)
                $0 stop
                $0 start
                ;;
        *)
                echo "Usage: $0 start|stop|restart|reload"
                exit 1
esac
exit 0
